### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by headwinds** [krunkosaurus/simg#2]
I like the idea behind this library but I'm a bit stumped on how to use it.

I'd like to help contribute a simple code example using its main features.

I've started to put together this:

http://headwinds.net/lab/simg/examples/simple/simple.html

As you can see, I'm stuck on step 1 - how do I setup up simg and pass in the svg? So that the simg library can consume it and turn it into a golden png?

I thought I would use Adobe's snap library to get the svg - I also tried D3 - not sure if I need to pass in the svg, the node, or something else...

**Comment by krunkosaurus** [comment]
Hi @headwinds! Thanks for the sample page. I have updated it so it works, pulled out unnecessary 3rd party libraries, and incorporated it into the repository with attribution to you. Please check out the code and let me know if you have any feedback or suggestions!

**Comment by headwinds** [comment]
fantastic! I really like what you did...

Can you host the example page on your server? So its easy for others to see that it works too. I’d turn the “example” into an “examples” folder starting with a sub “simple” or “getting started” folder.  I want to provide a more complex example down the road and other devs might like to do likewise.

Prior to discovering your library, I was messing about with phantomjs to a take screen shot of the visualization which works but it feels like overkill and its challenging to setup the page properly in the headless browser instead of simply capturing the svg element when its ready like your library does.

This afternoon, I also played with https://github.com/MrRio/jsPDF attempting to take the generated  image wrap it in some html and then insert into a pdf. Now, that I have the image - thanks to your explanation of Simg - I’m well on my way to completing my task for this week.  My product manager is pumped by the results after I emailed him the awesome.png from your working example ;-D 

Instead of one circle with no effects, I will be testing it against our full product next ( https://www.youtube.com/watch?v=9rsOKPK1oCk ).  

I think I’ll be able to provide a much more complex svg example later on which will include text, images, other shapes, even filters after I scrub the data for anything sensitive; or possibly use the http://exposedata.com/marvel/ instead...

Thanks for creating Simg!

**Comment by krunkosaurus** [comment]
The product looks cool. I originally pulled out this small library out of a bigger data visualization library I was working on for @keen.io  That product never got released in its current form but hopefully I can release an open source version of it in the future.

I went ahead and uploaded the example page as a gh-page.  You can find it at http://krunkosaurus.github.io/simg/

I'll leave just the `example` folder in for now but if you want to send a pull request in the future with more advanced examples feel free to and I'll pull it in and make those changes in the future.

**Comment by headwinds** [comment]
You might be right - actually having one example would showcase its power - that it works universally with any svg one may throw at it
