### ISSUE TITLE
Downloaded image not showing svg line gradients

### ISSUE THREAD

**Issue by arjun010** [krunkosaurus/simg#3]
I'm trying to use the library to download my graph (network) visualization as a png image. The nodes are appearing in the image but the links are missing. The links in my case are drawn using paths and each of these paths have a gradient attached to them which goes from the first node's color to the second node's color.

Any idea what could be going wrong?

**Comment by krunkosaurus** [comment]
Hi, sorry for the delay. Do you have a working sample webpage with this code?

**Comment by arjun010** [comment]
Hey, so I figured the issue. I was using CSS to style my links and this CSS was not being included in the downloaded image. 

I referred to http://spin.atomicobject.com/2014/01/21/convert-svg-to-png/ and got it working. You might want to look at adding this bit in to the library. If not, I can try doing it at a later point in time. Thanks for this library. It's a good utility.

**Comment by krunkosaurus** [comment]
Good tip. I've busy at the moment but I will look to adding this in the future. 

Thanks!
