### ISSUE TITLE
Not working if a <foreignObject> is present?

### ISSUE THREAD

**Issue by jiiins** [krunkosaurus/simg#7]
This SVG string (generated with chartist.js) doesn't get converted:
`<svg width="100%" height="100%" id="ct-chart-line" style="width: 100%; height: 100%;" version="1.1" xmlns="http://www.w3.org/2000/svg"><g class="ct-grids"></g><g><g series-name="benchmark" class="ct-series ct-series-a"><path d="M52,62.143L74.333,60.714L96.667,59.286L119,57.857L141.333,56.429L163.667,55L186,53.571L208.333,52.143L230.667,50.714L253,49.286L275.333,47.857L297.667,46.429L320,45" class="ct-line"></path></g><g series-name="performance" class="ct-series ct-series-b"><path d="M52,62.143L74.333,49.286L96.667,105L119,40.714L141.333,45L163.667,30.714L186,26.429L208.333,30.714L230.667,29.286L253,23.571L275.333,29.286L297.667,23.571L320,5" class="ct-line"></path></g></g><g class="ct-labels"><foreignObject style="overflow: visible;" x="42" y="110" width="22.333333333333332" height="20"><span class="ct-label ct-horizontal ct-end" style="width: 22px; height: 20px" xmlns="http://www.w3.org/2000/xmlns/"></span></foreignObject><foreignObject style="overflow: visible;" x="64.33333333333333" y="110" width="22.333333333333332" height="20"><span class="ct-label ct-horizontal ct-end" style="width: 22px; height: 20px" xmlns="http://www.w3.org/2000/xmlns/">Jan</span></foreignObject><foreignObject style="overflow: visible;" x="86.66666666666666" y="110" width="22.333333333333336" height="20"><span class="ct-label ct-horizontal ct-end" style="width: 22px; height: 20px" xmlns="http://www.w3.org/2000/xmlns/">Feb</span></foreignObject><foreignObject style="overflow: visible;" x="109" y="110" width="22.33333333333333" height="20"><span class="ct-label ct-horizontal ct-end" style="width: 22px; height: 20px" xmlns="http://www.w3.org/2000/xmlns/">Mar</span></foreignObject><foreignObject style="overflow: visible;" x="131.33333333333331" y="110" width="22.33333333333333" height="20"><span class="ct-label ct-horizontal ct-end" style="width: 22px; height: 20px" xmlns="http://www.w3.org/2000/xmlns/">Apr</span></foreignObject><foreignObject style="overflow: visible;" x="153.66666666666666" y="110" width="22.333333333333343" height="20"><span class="ct-label ct-horizontal ct-end" style="width: 22px; height: 20px" xmlns="http://www.w3.org/2000/xmlns/">May</span></foreignObject><foreignObject style="overflow: visible;" x="176" y="110" width="22.333333333333314" height="20"><span class="ct-label ct-horizontal ct-end" style="width: 22px; height: 20px" xmlns="http://www.w3.org/2000/xmlns/">Jun</span></foreignObject><foreignObject style="overflow: visible;" x="198.33333333333331" y="110" width="22.333333333333343" height="20"><span class="ct-label ct-horizontal ct-end" style="width: 22px; height: 20px" xmlns="http://www.w3.org/2000/xmlns/">Jul</span></foreignObject><foreignObject style="overflow: visible;" x="220.66666666666666" y="110" width="22.333333333333343" height="20"><span class="ct-label ct-horizontal ct-end" style="width: 22px; height: 20px" xmlns="http://www.w3.org/2000/xmlns/">Aug</span></foreignObject><foreignObject style="overflow: visible;" x="243" y="110" width="22.333333333333314" height="20"><span class="ct-label ct-horizontal ct-end" style="width: 22px; height: 20px" xmlns="http://www.w3.org/2000/xmlns/">Sep</span></foreignObject><foreignObject style="overflow: visible;" x="265.3333333333333" y="110" width="22.333333333333343" height="20"><span class="ct-label ct-horizontal ct-end" style="width: 22px; height: 20px" xmlns="http://www.w3.org/2000/xmlns/">Oct</span></foreignObject><foreignObject style="overflow: visible;" x="287.66666666666663" y="110" width="22.333333333333343" height="20"><span class="ct-label ct-horizontal ct-end" style="width: 22px; height: 20px" xmlns="http://www.w3.org/2000/xmlns/">Nov</span></foreignObject><foreignObject style="overflow: visible;" x="310" y="110" width="30" height="20"><span class="ct-label ct-horizontal ct-end" style="width: 30px; height: 20px" xmlns="http://www.w3.org/2000/xmlns/">Dec</span></foreignObject></g></svg>`

No errors... simply "nothing happens". By removing the `<foreignObject>` elements it works fine.

**Comment by krunkosaurus** [comment]
Hi, in general if you can't see the SVG in a regular webpage you can't convert it to an image. I pasted your code to a regular HTML page and couldn't view it so that's prob why it doesn't work. I'm not familiar with this SVG tag but my research shows its supposed to be rendered by a different user agent not the browser? https://developer.mozilla.org/en-US/docs/Web/SVG/Element/foreignObject

In any case I will close this issue as not possible to support.
